name: ezuq-env
channels:
  - conda-forge
  - rmg
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.24
  - scipy>=1.10
  - pyyaml>=6.0
  - cantera>=3.0
  - rmgpy
  - salib>=1.4
  - pip
  - pip:
    - pytest
    - pytest-cov
    - pycodestyle